# Tailscale, and an sshd that is reachable over it and nowhere else.
#
# The point of this pair is being able to reach this machine from anywhere,
# including from a trip long enough that authentication would otherwise lapse.
{ lib, pkgs, ... }:

{
  services.tailscale = {
    enable = true;

    # MagicDNS would rewrite /etc/resolv.conf and fight pihole.nix, which pins
    # the resolver to 127.0.0.1 on purpose. Declining it keeps Pi-hole as the
    # single resolver; pihole.nix conditionally forwards the tailnet zones to
    # 100.100.100.100 instead, which tailscaled serves either way. So .ts.net
    # names still resolve, through Pi-hole.
    #
    # --operator is what lets Trayscale work at all. tailscaled's control socket
    # is root-owned, so without naming an operator every state change from the
    # GUI either fails or needs a root prompt; with it, `dennis` can drive
    # tailscaled directly. It also makes plain `tailscale up`/`down` work without
    # sudo from a normal shell.
    extraSetFlags = [
      "--accept-dns=false"
      "--operator=dennis"
    ];
  };

  environment.systemPackages = [ pkgs.trayscale ];

  systemd.user.services.trayscale = {
    description = "Trayscale, a Tailscale GUI";
    wantedBy = [ "graphical-session.target" ];
    partOf = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${lib.getExe pkgs.trayscale} --hide-window";
      Restart = "on-failure";
      RestartSec = 3;
    };
  };

  services.openssh = {
    enable = true;

    openFirewall = false;

    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Tailscale brings this interface up itself; the rule is inert until it exists.
  networking.firewall.interfaces."tailscale0".allowedTCPPorts = [ 22 ];

  # Public keys; the second is Termius on the phone.
  users.users.dennis.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+DyXEJ10jky82r5N2yCxXF2GkkF1XlMttQepLOIwHi denni01wolfe@gmail.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGongqpx5cD/I67o+iiYxr/rMCpd9FMWwp5rnYafAc4t Generated By Termius"
  ];
}
